---
- name: install iptables
  apt:
    name: iptables
    state: present
    update_cache: yes

- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes

- name: Enable IPv4 forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward=1"
    create: yes

- name: Apply sysctl changes
  command: sysctl -p

- name: Get default network interface
  shell: "ip -o -4 route show to default | awk '{print $5}'"
  register: default_iface
  changed_when: false

- name: Configure NAT with iptables
  command: "iptables -t nat -A POSTROUTING -o {{ default_iface.stdout }} -j MASQUERADE"
  args:
    executable: /bin/bash

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4