---
- name: Setup newly created instances
  become: yes
  hosts: all
  tasks:
    - name: Seting up the NAT server
      include_tasks: tasks/nat.yml
      when: "'nat_servers' in group_names"

    - name: Installing docker on the cluster servers
      include_tasks: tasks/docker.yml
      when: "'cluster_hosts' in group_names"

    - name: Running Nginx on the servers
      include_tasks: tasks/nginx.yml
      when: "'cluster_hosts' in group_names"  

    - name: Creating vhosts on NAT
      include_tasks: tasks/vhosts.yml
      when: "'nat_servers' in group_names"