name: Deploy terraform infrastructure
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-south-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.2"  

      - name: Download Artifact
        uses: badgerhobbs/terraform-state@v2
        with:
            operation: download
            location: artifact
        continue-on-error: true

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform apply
        working-directory: terraform
        run: terraform destroy --auto-approve
    
      - name: Upload Artifact
        uses: badgerhobbs/terraform-state@v2
        with:
            operation: upload
            location: artifact

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_ed25519
          echo -e "${{secrets.SYS_ADM_SSHKEY}}" > ~/.ssh/id_ed25519
          chmod -R go= ~/.ssh

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.0
        with:
          version: "2.14.16"

      - name: Run ansible setup
        working-directory: ansible
        run: |
          ansible-playbook -i cluster_hosts.ini setup.yml --user admin --private-key ~/.ssh/id_ed25519