name: Deploy terraform infrastructure
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-south-1
      TF_WORKSPACE: ci-edit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.2"  

      - name: Download Artifact
        uses: badgerhobbs/terraform-state@v2
        with:
            operation: download
            location: artifact
            directory: terraform
        continue-on-error: true

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -auto-approve
    
      - name: Upload Artifact
        uses: badgerhobbs/terraform-state@v2
        with:
            operation: upload
            location: artifact
            directory: terraform

      - name: Upload Artifact
        uses: badgerhobbs/terraform-state@v2
        with:
            operation: upload
            location: artifact
            directory: terraform

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_ed25519
          echo -e "${{secrets.SYS_ADM_SSHKEY}}" > ~/.ssh/id_ed25519
          chmod -R go= ~/.ssh